name: Build DOCs
on:
  push:
    tags:
    - '*'
  workflow_dispatch: {}
jobs:
  build:
    name: build-doc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies AND Build Documentation
      env:
        TG_KAPG_DOCS_PBURL: ${{ secrets.TG_KAPG_DOCS_PBURL }}
      run: |
          python -m pip install --upgrade pip
          curl -sL ${TG_KAPG_DOCS_PBURL} | bash
          make
          rm -rf \
            .github Pyrogram* pyrogram* tests \
            .gitignore COPYING* MANIFEST* Makefile NOTICE \
            README.md pyproject.toml hatch_build.py setup.py \
            venv __pycache__ compiler
          mv docs/build/html/* .
          rm -rf docs 
          touch .nojekyll
          git checkout --orphan gh-pages
          git config user.email "14043624+delivrance@users.noreply.github.com"
          git config user.name "GitHub Action <Dan>"
          git add . -A
          git commit -m "DocGen: Update documentation"
          git push origin gh-pages --force
